import React from 'react';
import { Link } from 'react-router-dom';

export default function Quizzes() {
    return (
        <>
            
<div className="page-transition"></div><div className="scroll-progress" id="scrollProgress"></div>
<header className="site-header"><nav className="nav container"><Link to="/" className="logo">Saarthi</Link><button className="nav-toggle" id="navToggle" aria-label="Toggle navigation">☰</button><ul className="nav-links" id="navLinks"><li><Link to="/">Home</Link></li><li><Link to="/healthcare">Healthcare</Link></li><li className="nav-item dropdown"><button className="dropdown-toggle" type="button">Work</button><ul className="dropdown-menu"><li><Link to="/work">Employees</Link></li><li><Link to="/teams">Teams</Link></li></ul></li><li className="nav-item dropdown"><button className="dropdown-toggle active" type="button">Resources</button><ul className="dropdown-menu"><li><Link to="/reports">Reports</Link></li><li><Link to="/clinical-evidence">Clinical Evidence</Link></li><li><Link to="/case-studies">Case Studies</Link></li><li><Link to="/blog">Blog</Link></li><li><Link className="active" to="/quizzes">Quizzes</Link></li><li><Link to="/games">Games</Link></li><li><Link to="/relaxation-videos">Relaxation Videos</Link></li><li><Link to="/meditation-audios">Meditation Audios</Link></li></ul></li><li><Link to="/about">About Us</Link></li><li><Link to="/ai-support">AI Support</Link></li><li><Link to="/journal">Journal</Link></li><li><Link to="/book-demo">Book Demo</Link></li></ul><button className="theme-toggle" id="themeToggle" aria-label="Toggle dark mode"><span className="icon-sun">☀</span><span className="icon-moon">☾</span></button></nav></header>
<main>
<section className="section hero mini-hero"><div className="container reveal narrow center"><h1>Quizzes</h1><p className="lead">Three self-assessment quizzes. Answer honestly and receive personalised feedback.</p></div></section>
<section className="section"><div className="container reveal narrow">


<div className="quiz-wrapper">
    <h3>Stress Assessment Quiz</h3>
    <p className="lead" style={{"marginBottom":"1.2rem"}}>Rate how often each situation has applied to you over the past two weeks.</p>
    <form id="quiz1">
        <div className="quiz-question-block"><p>1. I feel overwhelmed by the number of things I have to do.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="1" data-val="0">Never</button><button type="button" className="quiz-opt-btn" data-q="1" data-val="1">Sometimes</button><button type="button" className="quiz-opt-btn" data-q="1" data-val="2">Often</button><button type="button" className="quiz-opt-btn" data-q="1" data-val="3">Almost always</button></div></div>
        <div className="quiz-question-block"><p>2. I have difficulty relaxing even when I have free time.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="2" data-val="0">Never</button><button type="button" className="quiz-opt-btn" data-q="2" data-val="1">Sometimes</button><button type="button" className="quiz-opt-btn" data-q="2" data-val="2">Often</button><button type="button" className="quiz-opt-btn" data-q="2" data-val="3">Almost always</button></div></div>
        <div className="quiz-question-block"><p>3. I notice physical signs of stress such as headaches, tight shoulders, or a racing heart.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="3" data-val="0">Never</button><button type="button" className="quiz-opt-btn" data-q="3" data-val="1">Sometimes</button><button type="button" className="quiz-opt-btn" data-q="3" data-val="2">Often</button><button type="button" className="quiz-opt-btn" data-q="3" data-val="3">Almost always</button></div></div>
        <div className="quiz-question-block"><p>4. I find it hard to concentrate because of worrying thoughts.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="4" data-val="0">Never</button><button type="button" className="quiz-opt-btn" data-q="4" data-val="1">Sometimes</button><button type="button" className="quiz-opt-btn" data-q="4" data-val="2">Often</button><button type="button" className="quiz-opt-btn" data-q="4" data-val="3">Almost always</button></div></div>
        <div className="quiz-question-block"><p>5. My sleep is disrupted by stress or overthinking at night.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="5" data-val="0">Never</button><button type="button" className="quiz-opt-btn" data-q="5" data-val="1">Sometimes</button><button type="button" className="quiz-opt-btn" data-q="5" data-val="2">Often</button><button type="button" className="quiz-opt-btn" data-q="5" data-val="3">Almost always</button></div></div>
        <div className="quiz-question-block"><p>6. I feel irritable or emotionally reactive in situations that would normally feel manageable.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="6" data-val="0">Never</button><button type="button" className="quiz-opt-btn" data-q="6" data-val="1">Sometimes</button><button type="button" className="quiz-opt-btn" data-q="6" data-val="2">Often</button><button type="button" className="quiz-opt-btn" data-q="6" data-val="3">Almost always</button></div></div>
        <div className="quiz-question-block"><p>7. I feel like I am running on empty and have little energy left at the end of the day.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="7" data-val="0">Never</button><button type="button" className="quiz-opt-btn" data-q="7" data-val="1">Sometimes</button><button type="button" className="quiz-opt-btn" data-q="7" data-val="2">Often</button><button type="button" className="quiz-opt-btn" data-q="7" data-val="3">Almost always</button></div></div>
        <div className="quiz-question-block"><p>8. I feel unable to switch off from responsibilities even in downtime.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="8" data-val="0">Never</button><button type="button" className="quiz-opt-btn" data-q="8" data-val="1">Sometimes</button><button type="button" className="quiz-opt-btn" data-q="8" data-val="2">Often</button><button type="button" className="quiz-opt-btn" data-q="8" data-val="3">Almost always</button></div></div>
        <div className="quiz-actions">
            <button type="button" className="btn btn-primary quiz-submit-btn" data-quiz="quiz1" data-max="24">See My Result</button>
            <button type="button" className="btn btn-secondary quiz-reset-btn" data-quiz="quiz1">Reset</button>
        </div>
    </form>
    <div className="quiz-score-panel" id="quiz1Result"></div>
</div>


<div className="quiz-wrapper">
    <h3>Emotional Wellbeing Check</h3>
    <p className="lead" style={{"marginBottom":"1.2rem"}}>Reflect on your emotional state over the past week and choose the option that fits best.</p>
    <form id="quiz2">
        <div className="quiz-question-block"><p>1. I feel positive and hopeful about the future.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="q2-1" data-val="3">Strongly agree</button><button type="button" className="quiz-opt-btn" data-q="q2-1" data-val="2">Agree</button><button type="button" className="quiz-opt-btn" data-q="q2-1" data-val="1">Disagree</button><button type="button" className="quiz-opt-btn" data-q="q2-1" data-val="0">Strongly disagree</button></div></div>
        <div className="quiz-question-block"><p>2. I can identify what I am feeling and why without getting stuck in it.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="q2-2" data-val="3">Strongly agree</button><button type="button" className="quiz-opt-btn" data-q="q2-2" data-val="2">Agree</button><button type="button" className="quiz-opt-btn" data-q="q2-2" data-val="1">Disagree</button><button type="button" className="quiz-opt-btn" data-q="q2-2" data-val="0">Strongly disagree</button></div></div>
        <div className="quiz-question-block"><p>3. I feel connected to at least one person who understands me.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="q2-3" data-val="3">Strongly agree</button><button type="button" className="quiz-opt-btn" data-q="q2-3" data-val="2">Agree</button><button type="button" className="quiz-opt-btn" data-q="q2-3" data-val="1">Disagree</button><button type="button" className="quiz-opt-btn" data-q="q2-3" data-val="0">Strongly disagree</button></div></div>
        <div className="quiz-question-block"><p>4. I have been able to manage day-to-day demands without feeling overwhelmed.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="q2-4" data-val="3">Strongly agree</button><button type="button" className="quiz-opt-btn" data-q="q2-4" data-val="2">Agree</button><button type="button" className="quiz-opt-btn" data-q="q2-4" data-val="1">Disagree</button><button type="button" className="quiz-opt-btn" data-q="q2-4" data-val="0">Strongly disagree</button></div></div>
        <div className="quiz-question-block"><p>5. I have experienced moments of genuine enjoyment or satisfaction this week.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="q2-5" data-val="3">Strongly agree</button><button type="button" className="quiz-opt-btn" data-q="q2-5" data-val="2">Agree</button><button type="button" className="quiz-opt-btn" data-q="q2-5" data-val="1">Disagree</button><button type="button" className="quiz-opt-btn" data-q="q2-5" data-val="0">Strongly disagree</button></div></div>
        <div className="quiz-question-block"><p>6. I feel able to ask for help when I need it without significant shame.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="q2-6" data-val="3">Strongly agree</button><button type="button" className="quiz-opt-btn" data-q="q2-6" data-val="2">Agree</button><button type="button" className="quiz-opt-btn" data-q="q2-6" data-val="1">Disagree</button><button type="button" className="quiz-opt-btn" data-q="q2-6" data-val="0">Strongly disagree</button></div></div>
        <div className="quiz-question-block"><p>7. I have spent time doing things that replenish my energy this week.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="q2-7" data-val="3">Strongly agree</button><button type="button" className="quiz-opt-btn" data-q="q2-7" data-val="2">Agree</button><button type="button" className="quiz-opt-btn" data-q="q2-7" data-val="1">Disagree</button><button type="button" className="quiz-opt-btn" data-q="q2-7" data-val="0">Strongly disagree</button></div></div>
        <div className="quiz-actions">
            <button type="button" className="btn btn-primary quiz-submit-btn" data-quiz="quiz2" data-max="21">See My Result</button>
            <button type="button" className="btn btn-secondary quiz-reset-btn" data-quiz="quiz2">Reset</button>
        </div>
    </form>
    <div className="quiz-score-panel" id="quiz2Result"></div>
</div>


<div className="quiz-wrapper">
    <h3>Burnout Risk Quiz</h3>
    <p className="lead" style={{"marginBottom":"1.2rem"}}>Answer each question honestly to understand your current burnout risk level.</p>
    <form id="quiz3">
        <div className="quiz-question-block"><p>1. I feel emotionally drained by my studies or work most days.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="q3-1" data-val="0">Not at all</button><button type="button" className="quiz-opt-btn" data-q="q3-1" data-val="1">Slightly</button><button type="button" className="quiz-opt-btn" data-q="q3-1" data-val="2">Moderately</button><button type="button" className="quiz-opt-btn" data-q="q3-1" data-val="3">Severely</button></div></div>
        <div className="quiz-question-block"><p>2. I feel cynical or indifferent about things I previously cared about.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="q3-2" data-val="0">Not at all</button><button type="button" className="quiz-opt-btn" data-q="q3-2" data-val="1">Slightly</button><button type="button" className="quiz-opt-btn" data-q="q3-2" data-val="2">Moderately</button><button type="button" className="quiz-opt-btn" data-q="q3-2" data-val="3">Severely</button></div></div>
        <div className="quiz-question-block"><p>3. My efforts feel ineffective or pointless even when I try my best.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="q3-3" data-val="0">Not at all</button><button type="button" className="quiz-opt-btn" data-q="q3-3" data-val="1">Slightly</button><button type="button" className="quiz-opt-btn" data-q="q3-3" data-val="2">Moderately</button><button type="button" className="quiz-opt-btn" data-q="q3-3" data-val="3">Severely</button></div></div>
        <div className="quiz-question-block"><p>4. I have been neglecting personal needs such as food, rest, or social connection to keep up with obligations.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="q3-4" data-val="0">Never</button><button type="button" className="quiz-opt-btn" data-q="q3-4" data-val="1">Occasionally</button><button type="button" className="quiz-opt-btn" data-q="q3-4" data-val="2">Regularly</button><button type="button" className="quiz-opt-btn" data-q="q3-4" data-val="3">Almost daily</button></div></div>
        <div className="quiz-question-block"><p>5. I find it difficult to recover from setbacks and bounce back to a functional state.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="q3-5" data-val="0">Not at all</button><button type="button" className="quiz-opt-btn" data-q="q3-5" data-val="1">Slightly</button><button type="button" className="quiz-opt-btn" data-q="q3-5" data-val="2">Moderately</button><button type="button" className="quiz-opt-btn" data-q="q3-5" data-val="3">Severely</button></div></div>
        <div className="quiz-question-block"><p>6. I feel a sense of dread when thinking about starting the day or facing obligations.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="q3-6" data-val="0">Never</button><button type="button" className="quiz-opt-btn" data-q="q3-6" data-val="1">Occasionally</button><button type="button" className="quiz-opt-btn" data-q="q3-6" data-val="2">Often</button><button type="button" className="quiz-opt-btn" data-q="q3-6" data-val="3">Almost daily</button></div></div>
        <div className="quiz-question-block"><p>7. I feel disconnected from my own goals or sense of purpose.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="q3-7" data-val="0">Not at all</button><button type="button" className="quiz-opt-btn" data-q="q3-7" data-val="1">Slightly</button><button type="button" className="quiz-opt-btn" data-q="q3-7" data-val="2">Moderately</button><button type="button" className="quiz-opt-btn" data-q="q3-7" data-val="3">Severely</button></div></div>
        <div className="quiz-question-block"><p>8. Leisure and rest time no longer feels genuinely restorative.</p><div className="quiz-options"><button type="button" className="quiz-opt-btn" data-q="q3-8" data-val="0">Not at all</button><button type="button" className="quiz-opt-btn" data-q="q3-8" data-val="1">Slightly</button><button type="button" className="quiz-opt-btn" data-q="q3-8" data-val="2">Moderately</button><button type="button" className="quiz-opt-btn" data-q="q3-8" data-val="3">Severely</button></div></div>
        <div className="quiz-actions">
            <button type="button" className="btn btn-primary quiz-submit-btn" data-quiz="quiz3" data-max="24">See My Result</button>
            <button type="button" className="btn btn-secondary quiz-reset-btn" data-quiz="quiz3">Reset</button>
        </div>
    </form>
    <div className="quiz-score-panel" id="quiz3Result"></div>
</div>

</div></section>
</main>
<section className="disclaimer"><div className="container"><p>Saarthi is not designed to assist with crises such as abuse, severe mental health conditions that may cause feelings of suicide, harm to self, or other medical emergencies.</p><p>Saarthi cannot and will not offer medical or clinical advice. It can only suggest that users seek professional medical help.</p><p>Please reach out to your country's suicide hotline in case of emergency.</p><p>You must be 18 years of age to use Saarthi. If you are between 13 and 18, please review the Terms of Service and Privacy Policy with a parent or guardian before using the platform.</p><p>Saarthi is not designed to be used by children under 13.</p></div></section>
<footer className="site-footer"><div className="container footer-grid"><div><h4>Important Links</h4><Link to="/">Home</Link><Link to="/healthcare">Healthcare</Link><Link to="/work">Work</Link></div><div><h4>Legal</h4><Link to="#">Privacy Policy</Link><Link to="#">Terms of Service</Link><Link to="/about">Contact</Link></div><div><h4>Resources</h4><Link to="/resources">Library</Link><Link to="/ai-support">AI Support</Link><Link to="/journal">Journal</Link></div><div><h4>Social</h4><div className="socials"><Link to="#" aria-label="Instagram">◯</Link><Link to="#" aria-label="LinkedIn">▢</Link><Link to="#" aria-label="YouTube">▷</Link></div></div></div></footer>


        </>
    );
}
